namespace: "sigp"
name: "lighthouse"
version: "0.0.1"
readme: "README.md"
authors:
    - "Sigma Prime <contact@sigmaprime.io>"
license:
    - "Apache 2.0"
tags:
    - ethereum
    - blockchain
    - lighthouse
