---
- name: Deploy lighthouse-bn.service
  become: yes
  template:
    src: ../templates/lighthouse-bn.service.j2
    dest: "{{ lighthouse_systemd_service_files_path }}/{{ lighthouse_beacon_systemd_service_name }}.service"
    force: yes

- name: Reload systemctl daemon
  become: yes
  command: systemctl daemon-reload
