---
- name: Restart and enable the validator client service
  become: yes
  systemd:
    name: "{{ lighthouse_validator_systemd_service_name }}"
    state: restarted
    enabled: yes
    daemon-reload: yes

