---
- name: Ensure destination binary directory exists
  file:
    path: "{{ lighthouse_bin_path }}"
    state: directory

- name: Check configuration
  block:
    - fail:
        msg: The `lighthouse_binary_on_ansible_controller` variable is not set.
      when: lighthouse_binary_on_ansible_controller is None

- name: Distribute pre-built lighthouse binary
  copy:
    src: "{{ lighthouse_binary_on_ansible_controller }}/lighthouse"
    dest: "{{ lighthouse_bin }}"
    mode: '744'
    force: yes

- name: Deploy lighthouse-bn.service
  become: yes
  template:
    src: ../templates/lighthouse-bn.service.j2
    dest: "{{ lighthouse_systemd_service_files_path }}/{{ lighthouse_beacon_systemd_service_name }}.service"
    force: yes

- name: Reload systemctl daemon
  become: yes
  command: systemctl daemon-reload

